hero.moveUp()
hero.moveRight()
hero.moveRight()
hero.moveUp()
hero.moveRight(5)
enemy = hero.findNearestEnemy()
while enemy:
    hero.attack(enemy)
    enemy = hero.findNearestEnemy()
hero.moveUp(3)
hero.moveLeft()
hero.moveDown(3)
hero.moveLeft(2)
enemy = hero.findNearestEnemy()
while enemy:
    hero.attack(enemy)
    enemy = hero.findNearestEnemy()
hero.moveUp(2)
enemy = hero.findNearestEnemy()
while enemy:
    hero.attack(enemy)
    enemy = hero.findNearestEnemy()
hero.moveDown(2)
hero.moveLeft(2)
enemy = hero.findNearestEnemy()
while enemy:
    hero.attack(enemy)
    enemy = hero.findNearestEnemy()
hero.moveUp(2)
enemy = hero.findNearestEnemy()
while enemy:
    hero.attack(enemy)
    enemy = hero.findNearestEnemy()
hero.moveDown(3)
hero.moveLeft(2)
hero.moveUp()
enemy = hero.findNearestEnemy()
while enemy:
    hero.attack(enemy)
    enemy = hero.findNearestEnemy()
hero.moveUp(2)
enemy = hero.findNearestEnemy()
while enemy:
    hero.attack(enemy)
    enemy = hero.findNearestEnemy()
hero.moveDown(3)
hero.moveRight(2)
hero.moveDown()