# https://codecombat.com/play/level/the-long-march
# Победи огров.
# Помни, что каждому из них нужно нанести два удара.
hero.attack('Rig')
hero.attack('Rig')
hero.attack('Gurt')
hero.attack('Gurt')
hero.attack('Ack')
hero.attack('Ack')
hero.moveRight(3)
hero.say('Secret')
hero.moveRight()
hero.moveUp(2)
hero.attack('Belch')
hero.attack('Belch')
hero.attack('Belch')
hero.attack('Belch')
hero.attack('Belch')
hero.moveUp(3)
hero.moveLeft(6)
