# http://codecombat.com/play/level/deadly-dungeon-rescue
# Сбегите из подземелья после спасения измученного крестьянина.
# Вы можете спрятаться за горгульями.
# Убийство охранников может привести к нежелательным последствиям.
# Если вы сможете собрать все сокровища, вы можете получить дополнительную награду.
self.moveUp(5)
self.moveRight(6)
self.moveDown(4)
self.moveRight(6)
self.moveDown(4)
self.attack('Torture Room Door')
self.attack('Torture Room Door')
self.attack('Torture Master')
self.attack('Torture Master')
self.moveRight(2)
self.moveDown(2)
self.moveLeft(8)
self.attack('South Vault Door')
self.attack('South Vault Door')
self.moveUp(2)
self.moveRight()
self.moveDown()
self.moveLeft(3)
self.moveRight()
self.moveUp(6)
self.moveLeft(2)
self.moveRight(2)
self.moveDown(4)
self.moveUp(4)
self.moveRight(2)
self.moveLeft(2)
self.moveDown(4)
self.moveUp(4)
self.moveDown(7)
self.moveLeft(3)
# self.moveRight(4)
# self.moveLeft(2)
self.moveUp(9)
self.moveRight(6)
self.moveDown(2)
self.attack('Exit Door')
self.attack('Exit Door')
self.moveRight(7)
# self.moveDown(4)
# self.attack('Torture Room Door')
# self.attack('Torture Room Door')
# self.moveLeft(2)
# self.moveRight(2)
