# https://codecombat.com/play/level/footsteps-in-a-maze
# Should fill in some default source
# Should fill in some default source
hero.moveRight()
hero.moveDown()
hero.moveLeft(4)
hero.moveUp(2)
hero.moveRight()
hero.moveDown()
hero.moveUp()
hero.moveLeft()
hero.moveDown(4)
hero.moveLeft()
hero.moveUp(5)
hero.moveRight(7)
hero.moveDown(5)
hero.moveUp(5)
hero.moveLeft(7)
hero.moveDown(5)
hero.moveRight(2)
hero.moveUp()
hero.moveRight()
hero.moveDown()
hero.moveRight(3)
hero.moveUp(1)
hero.moveLeft(2)
hero.moveRight(2)
hero.moveUp(3)
hero.moveLeft(3)
hero.moveDown()
