enemy = self.findNearestEnemy();
self.attack(enemy);
self.attack(enemy);
enemy = self.findNearestEnemy();
self.attack(enemy);
self.attack(enemy);
self.moveRight();
self.moveDown();
self.moveRight();
self.moveUp();
