enemy1 = hero.findNearestEnemy()
hero.attack(enemy1)
hero.attack(enemy1)
enemy2 = hero.findNearestEnemy()
hero.attack(enemy2)
hero.attack(enemy2)
enemy3 = hero.findNearestEnemy()
hero.attack(enemy3)
hero.attack(enemy3)
