enemy1 = self.findNearestEnemy()
self.attack(enemy1)
self.attack(enemy1)
enemy2 = self.findNearestEnemy()
self.attack(enemy2)
self.attack(enemy2)
enemy3 = self.findNearestEnemy()
self.attack(enemy3)
self.attack(enemy3)
